package models

const (
	QwenQwen3_32B        ModelID = "qwen-qwen3-32b"
	QwenQwen3_8B         ModelID = "qwen-qwen3-8b"
	QwenQwen3_4B         ModelID = "qwen-qwen3-4b"
	QwenQwen3_0_5B       ModelID = "qwen-qwen3-0.5b"
	QwenQwen3_235B_A14B  ModelID = "qwen-qwen3-235b-a14b"
	QwenQwen3_110B       ModelID = "qwen-qwen3-110b"
	QwenQwen3_Coder_Plus ModelID = "qwen3-coder-plus"
	QwenQwen2_5_72B      ModelID = "qwen2.5-72b"
	QwenQwen2_5_32B      ModelID = "qwen2.5-32b"
	QwenQwen2_5_14B      ModelID = "qwen2.5-14b"
	QwenQwen2_5_7B       ModelID = "qwen2.5-7b"
	QwenQwen2_5_1_8B     ModelID = "qwen2.5-1.8b"
	QwenQwen2_5_0_5B     ModelID = "qwen2.5-0.5b"
	QwenQwen2_5_Coder_32B ModelID = "qwen2.5-coder-32b"
	QwenQwen2_5_Coder_7B  ModelID = "qwen2.5-coder-7b"
	QwenQwen2_5_Math_72B  ModelID = "qwen2.5-math-72b"
	QwenQwen2_5_Math_7B   ModelID = "qwen2.5-math-7b"
	QwenQwen2_VL_72B      ModelID = "qwen2-vl-72b"
	QwenQwen2_VL_32B      ModelID = "qwen2-vl-32b"
	QwenQwen2_VL_7B       ModelID = "qwen2-vl-7b"
)

var QwenModels = map[ModelID]Model{
	QwenQwen3_32B: {
		ID:                  QwenQwen3_32B,
		Name:                "Qwen3 32B",
		Provider:            ProviderQwen,
		APIModel:            "qwen3-32b",
		CostPer1MIn:         0.5,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        1.5,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen3_8B: {
		ID:                  QwenQwen3_8B,
		Name:                "Qwen3 8B",
		Provider:            ProviderQwen,
		APIModel:            "qwen3-8b",
		CostPer1MIn:         0.2,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        0.6,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen3_4B: {
		ID:                  QwenQwen3_4B,
		Name:                "Qwen3 4B",
		Provider:            ProviderQwen,
		APIModel:            "qwen3-4b",
		CostPer1MIn:         0.1,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        0.3,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen3_0_5B: {
		ID:                  QwenQwen3_0_5B,
		Name:                "Qwen3 0.5B",
		Provider:            ProviderQwen,
		APIModel:            "qwen3-0.5b",
		CostPer1MIn:         0.1,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        0.1,
		ContextWindow:       32_768,
		DefaultMaxTokens:    4_000,
		SupportsAttachments: true,
	},
	QwenQwen3_235B_A14B: {
		ID:                  QwenQwen3_235B_A14B,
		Name:                "Qwen3 235B A14B",
		Provider:            ProviderQwen,
		APIModel:            "qwen3-235b-a14b",
		CostPer1MIn:         1.5,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        4.5,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen3_110B: {
		ID:                  QwenQwen3_110B,
		Name:                "Qwen3 110B",
		Provider:            ProviderQwen,
		APIModel:            "qwen3-110b",
		CostPer1MIn:         1.0,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        3.0,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen3_Coder_Plus: {
		ID:                  QwenQwen3_Coder_Plus,
		Name:                "Qwen3 Coder Plus",
		Provider:            ProviderQwen,
		APIModel:            "qwen3-coder-plus",
		CostPer1MIn:         0.5,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        1.5,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen2_5_72B: {
		ID:                  QwenQwen2_5_72B,
		Name:                "Qwen2.5 72B",
		Provider:            ProviderQwen,
		APIModel:            "qwen2.5-72b",
		CostPer1MIn:         0.9,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        2.7,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen2_5_32B: {
		ID:                  QwenQwen2_5_32B,
		Name:                "Qwen2.5 32B",
		Provider:            ProviderQwen,
		APIModel:            "qwen2.5-32b",
		CostPer1MIn:         0.5,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        1.5,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen2_5_14B: {
		ID:                  QwenQwen2_5_14B,
		Name:                "Qwen2.5 14B",
		Provider:            ProviderQwen,
		APIModel:            "qwen2.5-14b",
		CostPer1MIn:         0.3,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        0.6,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen2_5_7B: {
		ID:                  QwenQwen2_5_7B,
		Name:                "Qwen2.5 7B",
		Provider:            ProviderQwen,
		APIModel:            "qwen2.5-7b",
		CostPer1MIn:         0.2,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        0.4,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen2_5_1_8B: {
		ID:                  QwenQwen2_5_1_8B,
		Name:                "Qwen2.5 1.8B",
		Provider:            ProviderQwen,
		APIModel:            "qwen2.5-1.8b",
		CostPer1MIn:         0.1,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        0.2,
		ContextWindow:       32_768,
		DefaultMaxTokens:    4_000,
		SupportsAttachments: true,
	},
	QwenQwen2_5_0_5B: {
		ID:                  QwenQwen2_5_0_5B,
		Name:                "Qwen2.5 0.5B",
		Provider:            ProviderQwen,
		APIModel:            "qwen2.5-0.5b",
		CostPer1MIn:         0.1,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        0.1,
		ContextWindow:       32_768,
		DefaultMaxTokens:    4_000,
		SupportsAttachments: true,
	},
	QwenQwen2_5_Coder_32B: {
		ID:                  QwenQwen2_5_Coder_32B,
		Name:                "Qwen2.5 Coder 32B",
		Provider:            ProviderQwen,
		APIModel:            "qwen2.5-coder-32b",
		CostPer1MIn:         0.5,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        1.5,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen2_5_Coder_7B: {
		ID:                  QwenQwen2_5_Coder_7B,
		Name:                "Qwen2.5 Coder 7B",
		Provider:            ProviderQwen,
		APIModel:            "qwen2.5-coder-7b",
		CostPer1MIn:         0.2,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        0.4,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen2_5_Math_72B: {
		ID:                  QwenQwen2_5_Math_72B,
		Name:                "Qwen2.5 Math 72B",
		Provider:            ProviderQwen,
		APIModel:            "qwen2.5-math-72b",
		CostPer1MIn:         0.9,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        2.7,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen2_5_Math_7B: {
		ID:                  QwenQwen2_5_Math_7B,
		Name:                "Qwen2.5 Math 7B",
		Provider:            ProviderQwen,
		APIModel:            "qwen2.5-math-7b",
		CostPer1MIn:         0.2,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        0.4,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen2_VL_72B: {
		ID:                  QwenQwen2_VL_72B,
		Name:                "Qwen2 VL 72B",
		Provider:            ProviderQwen,
		APIModel:            "qwen2-vl-72b",
		CostPer1MIn:         0.9,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        2.7,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen2_VL_32B: {
		ID:                  QwenQwen2_VL_32B,
		Name:                "Qwen2 VL 32B",
		Provider:            ProviderQwen,
		APIModel:            "qwen2-vl-32b",
		CostPer1MIn:         0.5,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        1.5,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
	QwenQwen2_VL_7B: {
		ID:                  QwenQwen2_VL_7B,
		Name:                "Qwen2 VL 7B",
		Provider:            ProviderQwen,
		APIModel:            "qwen2-vl-7b",
		CostPer1MIn:         0.2,
		CostPer1MInCached:   0,
		CostPer1MOutCached:  0,
		CostPer1MOut:        0.4,
		ContextWindow:       32_768,
		DefaultMaxTokens:    8_000,
		SupportsAttachments: true,
	},
}
